version: 3.7
services:
  config:
    build:
      context: ./
      dockerfile: mpback-config-server/Dockerfile
    ports:
      - 9090
    networks:
      - mpback
  eureka:
    build:
      context: ./
      dockerfile: mpback-eureka-server/Dockerfile
    depends_on:
      - config
    ports:
      - 8761
    networks:
      - mpback
  mongodb:
    build:
      image: tutum/mongodb
      ports:
        - 27017
        - 28017
    depends_on:
      - eureka
    environment:
      - AUTH: no
  ocorrencia-server:
    build:
      context: ./
      dockerfile: mpback-ocorrencia-server/Dockerfile
    depends_on:
      - eureka
      - config
    ports:
      - 8080
    networks:
      - mpback
networks:
  mpback: