version: 3.7
services:
  eureka:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8761
    networks:
      - mpback
  config:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9090
    networks:
      - mpback
  ocorrencia-server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - config
    ports:
      - 8080
    networks:
      - mpback
networks:
  mpback: