version: "3"
services:

  config-server:
    build:
      context: ./mpback-config-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: always
    networks:
      - mpback
   
  eureka-server:
    build:
      context: ./mpback-eureka-server
      dockerfile: Dockerfile
    depends_on:
      - config-server
    hostname: eureka
    ports:
      - "9091:9091"
    restart: always
    networks:
      - mpback

  gateway-server:
    build:
      context: ./mpback-gateway-server
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - eureka-server
      - ocorrencia-server
    restart: always
    ports:
      - "9094:9094"
    networks:
      - mpback

  mongodb:
    image: mongo:3.4.20-xenial
    ports:
      - "27017:27017"
      - "28017:28017"
    restart: always
    networks:
      - mpback

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mpback

  ocorrencia-server:
    build:
      context: ./mpback-ocorrencia-server
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "9093:9093"
    restart: always
    networks:
      - mpback
    
networks:
  mpback: