version: "3.7"
services:
  config:
    build:
      context: ./mpback-config-server
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    networks:
      - mpback
  eureka:
    build:
      context: ./mpback-eureka-server
      dockerfile: Dockerfile
    depends_on:
      - config
    ports:
      - 9091:9091
    networks:
      - mpback
  gateway:
    build:
      context: ./mpback-gateway-server
      dockerfile: Dockerfile
    depends_on:
      - config
      - eureka
    ports:
      - 9094:9094
  mongodb:
    image: mongo:3.4.20-xenial
    ports:
      - 27017:27017
      - 28017:28017
    depends_on:
      - eureka
    restart: always
    networks:
      - mpback
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mpback
  ocorrencia-server:
    build:
      context: ./mpback-ocorrencia-server
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - config
    ports:
      - 9093:9093
    networks:
      - mpback
networks:
  mpback: