version: "3.7"
services:
  config-server:
    image: mpback_config
    ports:
      - "9090:9090"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - mpback
  eureka-server:
    image: mpback_eureka
    depends_on:
      - config
    hostname: eureka
    ports:
      - "9091:9091"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - mpback
  gateway-server:
    image: mpback_gateway
    depends_on:
      - config
      - eureka
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9094:9094"
    networks:
      - mpback
  mongodb:
    image: mongo:3.4.20-xenial
    ports:
      - "27017:27017"
      - "28017:28017"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - mpback
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mpback
  ocorrencia-server:
    image: mpback_ocorrencia-server
    depends_on:
      - eureka
      - config
    ports:
      - "9093:9093"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - mpback
  notification-service:
    image: joaoaneto/mp-notification-service:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9095:9095"
    networks:
      - mpback
    env_file: './mp-notification-service.env'

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - mpback


networks:
  mpback: