version: "3.7"
services:
  config:
    build:
      context: ./mpback-config-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - mpback
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 9091
  eureka:
    build:
      context: ./mpback-eureka-server
      dockerfile: Dockerfile
    depends_on:
      - config
    hostname: eureka
    ports:
      - "9091:9091"
    networks:
      - mpback
  gateway:
    build:
      context: ./mpback-gateway-server
      dockerfile: Dockerfile
    depends_on:
      - config
      - eureka
    ports:
      - "9094:9094"
    networks:
      - mpback
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 9091
  mongodb:
    image: mongo:3.4.20-xenial
    ports:
      - "27017:27017"
      - "28017:28017"
    restart: always
    networks:
      - mpback
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 9091
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      EUREKA_HOST: eureka
      EUREKA_PORT: 9091
    networks:
      - mpback
  ocorrencia-server:
    build:
      context: ./mpback-ocorrencia-server
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - config
    ports:
      - "9093:9093"
    networks:
      - mpback
    environment:
      EUREKA_HOST: eureka
      EUREKA_PORT: 9091
networks:
  mpback: